// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaGwLCu62sEBQ1lGRP8zhE_gT64tCMWmU',
    appId: '1:292450397595:web:7167a7f15fd910f032853e',
    messagingSenderId: '292450397595',
    projectId: 'chatapp-auth-cf311',
    authDomain: 'chatapp-auth-cf311.firebaseapp.com',
    storageBucket: 'chatapp-auth-cf311.appspot.com',
    measurementId: 'G-VSLEEJSB08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuH9MsOq5JZztpNMWJ6yPz4mpHoh50nc0',
    appId: '1:292450397595:android:b2b2ddc078c765c832853e',
    messagingSenderId: '292450397595',
    projectId: 'chatapp-auth-cf311',
    storageBucket: 'chatapp-auth-cf311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-LNtpeERU2ENx_AriTkYnJglzFRhU0mQ',
    appId: '1:292450397595:ios:cd3a20e0e81973ee32853e',
    messagingSenderId: '292450397595',
    projectId: 'chatapp-auth-cf311',
    storageBucket: 'chatapp-auth-cf311.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-LNtpeERU2ENx_AriTkYnJglzFRhU0mQ',
    appId: '1:292450397595:ios:7d203443902b16fc32853e',
    messagingSenderId: '292450397595',
    projectId: 'chatapp-auth-cf311',
    storageBucket: 'chatapp-auth-cf311.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
